# Site settings
title: Marcel Oomens
subtitle: Itinerant technologist and programmer
description: "Individuals and interactions over processes and tools. Not only individuals and interactions, but also a community of professionals."
avatar: "/images/avatar.jpg"
email: mail@marceloomens.com
mobile: +31 6 1858 8374
baseurl: "/"
url: "www.marceloomens.com"
timezone: Europe/Amsterdam
twitter_username: marceloomens
github_username:  marceloomens

# Build settings
exclude: [source]
markdown: kramdown
permalink: pretty

