# Site settings
title: Marcel Oomens
subtitle: itinerant technologist and programmer
description: "Itinerant technologist and programmer, news junkie, long-distance runner, collects books and has a love for travel and languages."
email: mail@marceloomens.com
mobile: +86 159 0102 7274
baseurl: ""
url: "http://marceloomens.com"
twitter_username: marceloomens
github_username:  marceloomens

# Build settings
exclude: [source]
markdown: kramdown
permalink: pretty

