# Site settings
title: Marcel Oomens
email: mail@marceloomens.com
description: "Itinerant technologist and programmer, news junkie, long-distance runner, collects books and has a love for travel and languages."
baseurl: ""
url: "http://marceloomens.com"
twitter_username: marceloomens
github_username:  marceloomens

# Build settings
exclude: [source]
markdown: kramdown
permalink: pretty

